# Generated by Django 3.0.3 on 2020-04-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sith',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sith_names', models.CharField(max_length=50)),
                ('planet', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('planet', models.CharField(max_length=250)),
                ('intergalactic_email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('notification', models.CharField(max_length=1000)),
                ('designated_sith', models.ManyToManyField(null=True, to='recruitment.Sith')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=1000)),
                ('answers', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('owned_by', models.ManyToManyField(null=True, to='recruitment.Sith')),
            ],
        ),
    ]
