# Generated by Django 3.0.3 on 2020-04-11 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='designated_sith',
        ),
        migrations.AddField(
            model_name='recruit',
            name='designated_sith',
            field=models.ManyToManyField(to='recruitment.Sith'),
        ),
    ]
