# Generated by Django 3.0.3 on 2020-04-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_auto_20200411_0355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='questions',
            name='owned_by',
            field=models.ManyToManyField(null=True, to='recruitment.Sith'),
        ),
        migrations.AlterField(
            model_name='recruit',
            name='designated_sith',
            field=models.ManyToManyField(null=True, to='recruitment.Sith'),
        ),
    ]
