# Generated by Django 3.0.3 on 2020-04-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_auto_20200411_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='notification',
        ),
        migrations.AddField(
            model_name='recruit',
            name='questions',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.Questions'),
            preserve_default=False,
        ),
    ]
